function BaseAlloy1Hz = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   BASEALLOY1HZ = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   BASEALLOY1HZ = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   BaseAlloy1Hz = importfile('Base_Alloy_1Hz.pos', 19, 1040);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/07/15 15:48:32

%% Initialize variables.
if nargin<=2
    startRow = 19;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10s%13s%15s%15s%11s%4s%4s%9s%9s%9s%9s%9s%9s%7s%7s%11s%11s%11s%10s%9s%9s%9s%9s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{2} = strtrim(dataArray{2});

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
    % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]);
rawStringColumns = string(raw(:, [1,2]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
idx = (rawStringColumns(:, 1) == "<undefined>");
rawStringColumns(idx, 1) = "";

%% Create output variable
BaseAlloy1Hz = table;
BaseAlloy1Hz.Program = categorical(rawStringColumns(:, 1));
BaseAlloy1Hz.RTKPOSTV = rawStringColumns(:, 2);
BaseAlloy1Hz.er243B34 = cell2mat(rawNumericColumns(:, 1));
BaseAlloy1Hz.VarName4 = cell2mat(rawNumericColumns(:, 2));
BaseAlloy1Hz.VarName5 = cell2mat(rawNumericColumns(:, 3));
BaseAlloy1Hz.VarName6 = cell2mat(rawNumericColumns(:, 4));
BaseAlloy1Hz.VarName7 = cell2mat(rawNumericColumns(:, 5));
BaseAlloy1Hz.VarName8 = cell2mat(rawNumericColumns(:, 6));
BaseAlloy1Hz.VarName9 = cell2mat(rawNumericColumns(:, 7));
BaseAlloy1Hz.VarName10 = cell2mat(rawNumericColumns(:, 8));
BaseAlloy1Hz.VarName11 = cell2mat(rawNumericColumns(:, 9));
BaseAlloy1Hz.VarName12 = cell2mat(rawNumericColumns(:, 10));
BaseAlloy1Hz.VarName13 = cell2mat(rawNumericColumns(:, 11));
BaseAlloy1Hz.VarName14 = cell2mat(rawNumericColumns(:, 12));
BaseAlloy1Hz.VarName15 = cell2mat(rawNumericColumns(:, 13));
BaseAlloy1Hz.VarName16 = cell2mat(rawNumericColumns(:, 14));
BaseAlloy1Hz.VarName17 = cell2mat(rawNumericColumns(:, 15));
BaseAlloy1Hz.VarName18 = cell2mat(rawNumericColumns(:, 16));
BaseAlloy1Hz.VarName19 = cell2mat(rawNumericColumns(:, 17));
BaseAlloy1Hz.VarName20 = cell2mat(rawNumericColumns(:, 18));
BaseAlloy1Hz.VarName21 = cell2mat(rawNumericColumns(:, 19));
BaseAlloy1Hz.VarName22 = cell2mat(rawNumericColumns(:, 20));
BaseAlloy1Hz.VarName23 = cell2mat(rawNumericColumns(:, 21));
BaseAlloy1Hz.VarName24 = cell2mat(rawNumericColumns(:, 22));

